name: CMake

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install libusb-1.0-0-dev
      run: sudo apt install -y --no-install-recommends libusb-1.0-0-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Package
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        cd ${{github.workspace}}/build
        tar -czvf ${{github.workspace}}/usb-hid-brightness-${{github.ref_name}}-x86_64.tar.gz usb-hid-brightness

    - name: Upload Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
          files: usb-hid-brightness-${{github.ref_name}}-x86_64.tar.gz
